spring.application.name=event-ingest-service

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# spring.jpa.hibernate.ddl-auto=update #não usar em produção

logging.level.com.zaxxer.hikari=DEBUG

jwt.secret="e3c9d860cbd5da050c57b4a402443a06c99208bcae2917e9bd36b2d5e8690fa9"
jwt.expiration=3600000
jwt.refresh-expiration=604800000